app:
  build: .
  links:
   - db
   - redis
  ports:
   - "8080:8080" # change to whatever port is to be used
  environment:
   - NODE_ENV=development # production for staging
  #env_file:
   #- ./server/config/development.env # required only if you have environment settings to load
db:
  image: mongo
  ports:
   - "27017:27017"
# Optional: if you are using Redis too, otherwise remove this section.
redis:
  image: redis
  ports:
   - "6379:6379"